apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./argocd-vault-plugin
- ./overlays/vault-service-account

patchesStrategicMerge:
  - patch-deployment-sa.yaml
# - argocd-repo-server-deploy.yaml
# - argocd-cm.yaml
