apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./namespace.yaml
- ./argocd-vault-plugin
- ./overlays/vault-service-account

patchesStrategicMerge:
  - patch-deployment-sa.yaml

# patchesJson6902:
# - target:
#     version: v1
#     kind: Deployment
#     name: my-deployment
#   patch: |-
#     - op: add
#       path: /rules/-
#       value:
#         apiGroups:
#           - ""
#         resources:
#           - ads
#         verbs:
#           - get
#           - list
#           - watch
